# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Curly Haired Guide to Curiosity
email: kazijehangir@gmail.com # change this when private email is feasible.
description: > # this means to ignore newlines until "baseurl:"
  Jehangir Kazi. A pretty big head and some thoughts to fill it.
  
  To-be-Googler. 
  
  "I love deadlines, I like the wooshing sound they make as they go by."
  - Douglas Adams

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jehangir.me" # the base hostname & protocol for your site
twitter_username: jehangir_kazi
github_username:  kazijehangir

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal
